version: '3' 

volumes: 
  data:

services:
  db:
    container_name: random_coffe_bot_db
    image: postgres:13.10
    env_file: .env 
    volumes: 
      - data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    container_name: backend 
    build: ./
    env_file: .env
    depends_on:
      - db
    command: >
      sh -c "alembic upgrade head &&
      python bot.py"
